set_property PACKAGE_PIN U20 [get_ports a_in]
set_property PACKAGE_PIN T19 [get_ports b_in]
set_property PACKAGE_PIN V20 [get_ports z_in]
set_property PACKAGE_PIN R18 [get_ports seg_a]
set_property PACKAGE_PIN N17 [get_ports seg_b]
set_property PACKAGE_PIN T20 [get_ports seg_c]
set_property PACKAGE_PIN R19 [get_ports seg_d]
set_property PACKAGE_PIN M17 [get_ports seg_e]
set_property PACKAGE_PIN P18 [get_ports seg_f]
set_property PACKAGE_PIN P19 [get_ports seg_g]
set_property PACKAGE_PIN P20 [get_ports seg_dp]
set_property PACKAGE_PIN M19 [get_ports seg_oe_n]
set_property PACKAGE_PIN L20 [get_ports seg_dig1]
set_property PACKAGE_PIN M18 [get_ports seg_dig2]
set_property PACKAGE_PIN L19 [get_ports seg_dig3]
set_property PACKAGE_PIN H18 [get_ports seg_dig4]
set_property PACKAGE_PIN D18 [get_ports seg_dig5]
set_property PACKAGE_PIN D20 [get_ports seg_dig6]
set_property PACKAGE_PIN B20 [get_ports motor_pul]
set_property PACKAGE_PIN H17 [get_ports motor_ena]
set_property PACKAGE_PIN C20 [get_ports motor_dir]


set_property IOSTANDARD LVCMOS33 [get_ports a_in]
set_property IOSTANDARD LVCMOS33 [get_ports b_in]
set_property IOSTANDARD LVCMOS33 [get_ports z_in]
set_property IOSTANDARD LVCMOS33 [get_ports seg_a]
set_property IOSTANDARD LVCMOS33 [get_ports seg_b]
set_property IOSTANDARD LVCMOS33 [get_ports seg_c]
set_property IOSTANDARD LVCMOS33 [get_ports seg_d]
set_property IOSTANDARD LVCMOS33 [get_ports seg_e]
set_property IOSTANDARD LVCMOS33 [get_ports seg_f]
set_property IOSTANDARD LVCMOS33 [get_ports seg_g]
set_property IOSTANDARD LVCMOS33 [get_ports seg_dp]
set_property IOSTANDARD LVCMOS33 [get_ports seg_oe_n]
set_property IOSTANDARD LVCMOS33 [get_ports seg_dig1]
set_property IOSTANDARD LVCMOS33 [get_ports seg_dig2]
set_property IOSTANDARD LVCMOS33 [get_ports seg_dig3]
set_property IOSTANDARD LVCMOS33 [get_ports seg_dig4]
set_property IOSTANDARD LVCMOS33 [get_ports seg_dig5]
set_property IOSTANDARD LVCMOS33 [get_ports seg_dig6]
set_property IOSTANDARD LVCMOS33 [get_ports motor_pul]
set_property IOSTANDARD LVCMOS33 [get_ports motor_ena]
set_property IOSTANDARD LVCMOS33 [get_ports motor_dir]







set_property PACKAGE_PIN K17 [get_ports {key[1]}]
set_property PACKAGE_PIN E19 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN W13 [get_ports {led[1]}]
set_property PACKAGE_PIN W14 [get_ports {led[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {key_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_led[0]}]
set_property PACKAGE_PIN K17 [get_ports {key_led[0]}]
set_property PACKAGE_PIN E19 [get_ports {key_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_sm[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_sm[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_sm[0]}]
set_property PACKAGE_PIN F20 [get_ports {key_sm[0]}]
set_property PACKAGE_PIN F19 [get_ports {key_sm[1]}]
set_property PACKAGE_PIN D19 [get_ports {key_sm[2]}]
